Rename and adjust rbenv to rsenv

diff --git a/libexec/rsenv-init b/libexec/rsenv-init
--- a/libexec/rsenv-init
+++ b/libexec/rsenv-init
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# Summary: Configure the shell environment for rbenv
-# Usage: eval "$(rbenv init - [--no-rehash] [<shell>])"
+# Summary: Configure the shell environment for rsenv
+# Usage: eval "$(rsenv init - [--no-rehash] [<shell>])"
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$RSENV_DEBUG" ] && set -x
 
 print=""
 no_rehash=""
@@ -30,7 +30,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "rsenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -73,15 +73,15 @@ if [ -z "$print" ]; then
     ;;
   esac
 
-  { echo "# Load rbenv automatically by adding"
+  { echo "# Load rsenv automatically by adding"
     echo "# the following to ${profile}:"
     echo
     case "$shell" in
     fish )
-      echo 'status --is-interactive; and . (rbenv init -|psub)'
+      echo 'status --is-interactive; and . (rsenv init -|psub)'
       ;;
     * )
-      echo 'eval "$(rbenv init -)"'
+      echo 'eval "$(rsenv init -)"'
       ;;
     esac
     echo
@@ -90,29 +90,29 @@ if [ -z "$print" ]; then
   exit 1
 fi
 
-mkdir -p "${RBENV_ROOT}/"{shims,versions}
+mkdir -p "${RSENV_ROOT}/"{shims,versions}
 
-if [[ ":${PATH}:" != *:"${RBENV_ROOT}/shims":* ]]; then
+if [[ ":${PATH}:" != *:"${RSENV_ROOT}/shims":* ]]; then
   case "$shell" in
   fish )
-    echo "setenv PATH '${RBENV_ROOT}/shims' \$PATH"
+    echo "setenv PATH '${RSENV_ROOT}/shims' \$PATH"
   ;;
   * )
-    echo 'export PATH="'${RBENV_ROOT}'/shims:${PATH}"'
+    echo 'export PATH="'${RSENV_ROOT}'/shims:${PATH}"'
   ;;
   esac
 fi
 
 case "$shell" in
 fish )
-  echo "setenv RBENV_SHELL $shell"
+  echo "setenv RSENV_SHELL $shell"
 ;;
 * )
-  echo "export RBENV_SHELL=$shell"
+  echo "export RSENV_SHELL=$shell"
 ;;
 esac
 
-completion="${root}/completions/rbenv.${shell}"
+completion="${root}/completions/rsenv.${shell}"
 if [ -r "$completion" ]; then
   case "$shell" in
   fish ) echo ". '$completion'" ;;
@@ -121,22 +121,22 @@ if [ -r "$completion" ]; then
 fi
 
 if [ -z "$no_rehash" ]; then
-  echo 'rbenv rehash 2>/dev/null'
+  echo 'rsenv rehash 2>/dev/null'
 fi
 
-commands=(`rbenv-commands --sh`)
+commands=(`rsenv-commands --sh`)
 case "$shell" in
 fish )
   cat <<EOS
-function rbenv
+function rsenv
   set command \$argv[1]
   set -e argv[1]
 
   switch "\$command"
   case ${commands[*]}
-    eval (rbenv "sh-\$command" \$argv)
+    eval (rsenv "sh-\$command" \$argv)
   case '*'
-    command rbenv "\$command" \$argv
+    command rsenv "\$command" \$argv
   end
 end
 EOS
@@ -144,13 +144,13 @@ EOS
   ;;
 ksh )
   cat <<EOS
-function rbenv {
+function rsenv {
   typeset command
 EOS
   ;;
 * )
   cat <<EOS
-rbenv() {
+rsenv() {
   local command
 EOS
   ;;
@@ -165,9 +165,9 @@ cat <<EOS
 
   case "\$command" in
   ${commands[*]})
-    eval "\`rbenv "sh-\$command" "\$@"\`";;
+    eval "\`rsenv "sh-\$command" "\$@"\`";;
   *)
-    command rbenv "\$command" "\$@";;
+    command rsenv "\$command" "\$@";;
   esac
 }
 EOS
diff --git a/libexec/rsenv-which b/libexec/rsenv-which
--- a/libexec/rsenv-which
+++ b/libexec/rsenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: rsenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that rsenv will invoke when
 # you run the given command.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$RSENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide rsenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec rsenv shims --short
 fi
 
 expand_path() {
@@ -48,37 +48,37 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+RSENV_VERSION="$(rsenv-version-name)"
+RSENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+if [ -z "$RSENV_COMMAND" ]; then
+  rsenv-help --usage which >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
+if [ "$RSENV_VERSION" = "system" ]; then
+  PATH="$(remove_from_path "${RSENV_ROOT}/shims")"
+  RSENV_COMMAND_PATH="$(command -v "$RSENV_COMMAND" || true)"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  RSENV_COMMAND_PATH="${RSENV_ROOT}/versions/${RSENV_VERSION}/bin/${RSENV_COMMAND}"
 fi
 
 OLDIFS="$IFS"
-IFS=$'\n' scripts=(`rbenv-hooks which`)
+IFS=$'\n' scripts=(`rsenv-hooks which`)
 IFS="$OLDIFS"
 for script in "${scripts[@]}"; do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$RSENV_COMMAND_PATH" ]; then
+  echo "$RSENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "rsenv: $RSENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(rsenv-whence "$RSENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
-      echo "The \`$1' command exists in these Ruby versions:"
+      echo "The \`$1' command exists in these Rust versions:"
       echo "$versions" | sed 's/^/  /g'
       echo
     } >&2
